//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInfo
    {
        public int LogInfoID { get; set; }
        public string LogType { get; set; }
        public string LogContent { get; set; }
        public Nullable<int> LogSysID { get; set; }
        public string LogIP { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public string LogPersonNum { get; set; }
        public string LogPersonName { get; set; }
        public string LogCol1 { get; set; }
        public string LogCol2 { get; set; }
        public string LogCol3 { get; set; }
        public string LogCol4 { get; set; }
        public string LogCol5 { get; set; }
    }
}
