//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysInfo
    {
        public int SysInfoID { get; set; }
        public string SysName { get; set; }
        public string SysDesc { get; set; }
        public string SysIcon { get; set; }
        public string TechnicalContactPhone { get; set; }
        public string TechnicalContactPerson { get; set; }
        public string ManageContactPhone { get; set; }
        public string ManageContactPerson { get; set; }
        public string SysState { get; set; }
        public string SysType { get; set; }
        public string SysTypeSub { get; set; }
        public string SysUrl { get; set; }
        public string LoginUrl { get; set; }
        public string LoginType { get; set; }
        public Nullable<double> SysOrder { get; set; }
        public string IsLogin { get; set; }
        public string LoginCheckDataBaseIP { get; set; }
        public string LoginCheckDataBaseName { get; set; }
        public string LoginCheckDataBaseUserName { get; set; }
        public string LoginCheckDataBaseUserPwd { get; set; }
        public string LoginCheckDataBaseStoredProcedure { get; set; }
    }
}
