//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysInfo
    {
        public int SysInfoID { get; set; }
        public string SysName { get; set; }
        public string SysDesc { get; set; }
        public string SysIcon { get; set; }
        public string ContactPhone { get; set; }
        public string ContactPerson { get; set; }
        public string SysState { get; set; }
        public string SysType { get; set; }
        public string LoginUrl { get; set; }
        public Nullable<double> SysOrder { get; set; }
    }
}
