//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemIntegration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSys
    {
        public int UserSysID { get; set; }
        public string UserNum { get; set; }
        public Nullable<int> SysInfoID { get; set; }
        public string BindState { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public Nullable<double> UserSysOrder { get; set; }
        public string LoginType { get; set; }
    }
}
